apiVersion: 1

datasources:
  - name: InfluxDB-SCADA
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: scada
      defaultBucket: scada
    secureJsonData:
      token: scada-dev-token
    isDefault: true
    editable: true
